version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - "8761:8761"
#    environment:
#      - RABBIT_SERVER_HOST=host.docker.internal
#      - RABBIT_SERVER_PORT=5672
#      - RABBIT_SERVER_USERNAME=guest
#      - RABBIT_SERVER_PASSWORD=guest
    networks:
        - workshop_network

networks:
    workshop_network: