spring:
  application:
    name: ${SPRING_APPLICATION_NAME:workshop_eureka_server}
#  rabbitmq:
#    host: ${SPRING_RABBITMQ_HOST:rabbitmq_server}
#    port: ${SPRING_RABBITMQ_PORT:5672}
#    username: ${SPRING_RABBITMQ_USERNAME:guest}
#    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

